{
 "title": "Port Scan",
 "tags": [
  "nmap-prometheus-exporter-dashboard",
  "https://github.com/vishnuvnn/nmap-prometheus-exporter"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cloud",
    "label": "Cloud",
    "query": "label_values(nmap_scan_results,cloud)"
   }
  ]
 },
 "panels": [
  {
   "title": "Scan info",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 4, "w": 12, "x": 6, "y": 0 },
   "options": {
    "content": "It took {{time_elapsed}} sec for scanning {{totalhosts}} hosts"
   },
   "targets": [
    {
     "expr": "nmap_scan_stats_info{cloud=\"$cloud\"}"
    }
   ]
  },
  {
   "title": "Host wise ports open",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(nmap_scan_results{cloud=\"$cloud\"}) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Types of ports open",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "count(nmap_scan_results{cloud=\"$cloud\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Port scan report",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nmap_scan_results{cloud=\"$cloud\"}"
    }
   ]
  }
 ]
}