version: '3'
services:
  nmap-prometheus-exporter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nmap-prometheus-exporter
    volumes:
# Mount the host file to the container -> change host path to your need
      - /path/to/your/portscanip.nmap:/app/portscanip.nmap
    ports:
      - "9808:9808"
    environment:
      - SCAN_FILE=/app/portscanip.nmap
      - EXPORTER_PORT=9808
      - SCAN_FREQUENCY=3600
    restart: always
    networks:
      - exporter_network

networks:
  exporter_network:
